title: Kerryl Musungu 
logo: "C:\Users\kerry\OneDrive\Images\Photo_Passeport_AJ.png"
description: Data Scientist| US Armed Forces DoD| Secret Clearance
show_downloads: True
theme: jekyll-theme-minimal
